import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import localFont from "next/font/local";

const recoleta = localFont({
  src: [
    {
      path: "../fonts/Recoleta-RegularDEMO.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Recoleta-RegularDEMO.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../fonts/Recoleta-RegularDEMO.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-recoleta",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${playfairDisplay.variable} ${recoleta.className}`}>
      <body className="font-sans">
        {children}
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
